name: Package updates

on:
  push:
  workflow_dispatch:

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: alpinelinux/aports
          path: aports
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone gearlock
        uses: actions/checkout@v3
        with:
          repository: Yuunix-Team/gearlock-core
          path: gearlock
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup
        uses: jirutka/setup-alpine@v1.1.3
      - name: Install deps
        run: |
          apk add abuild abuild-rootbld findutils sed grep gawk coreutils 
          cd aports
          find main community -name APKBUILD -exec sed -ri -e 's|pkgdir"/lib(64)?/|pkgdir"/usr/lib/|g' -e 's|pkgdir"/s?bin/|pkgdir"/usr/bin/|g' -e 's|amove lib/|amove usr/lib|g' -e 's|amove s?bin/|amove usr/bin|g' {} +
          echo -e "\n" | abuild-keygen
          cd ..
          addgroup abuild || true
          addgroup $USER abuild || true
        shell: alpine.sh --root {0}
      - name: Build
        run: |
          export CBUILD=x86_64
          export PACKAGER_PRIVKEY=$(ls -d ~/.abuild/*.rsa | head -1)
          mkdir pkgs
          dist=$(ls -d ./pkgs)
          export REPODEST=$dist
          cd aports
          for repo in main community; do
            cd $repo
            for pkg in alpine-baselayout-data busybox busybox-binsh alpine-baselayout alpine-keys ca-certificates-bundle ssl_client zlib apk-tools axel ncurses-terminfo-base ncurses-libs readline bash brotli-libs brotli libblkid lzo libuuid zstd-libs btrfs-progs cpulimit argon2-libs device-mapper-libs json-c cryptsetup-libs popt cryptsetup dialog libcom_err e2fsprogs-libs e2fsprogs e2fsprogs-extra xz-libs kmod scanelf lddtree mdev-conf kmod-libs nlplug-findfs mkinitfs grub grub-bios grub-efi musl-utils libc-utils libbz2 libgcc lz4-libs lrzip lz4 lzop libffi libintl libmount pcre2 glib gpm-libs pcre slang libssh2 mc nano ncurses ntfs-3g-libs ntfs-3g os-prober p7zip parted xz zstd hwdata-pci pciutils-libs pciutils libgpg-error libassuan pinentry libgcrypt gnupg-gpgconf gmp nettle libunistring libidn2 p11-kit libtasn1 gnutls libksba gdbm libsasl libldap npth gnupg-dirmngr sqlite-libs gnupg-keyboxd gpg gpg-agent gpg-wks-server gpgsm gpgv gnupg-utils gnupg-wks-client gnupg squashfs-tools libcrypto3 libssl3 libstdc++ openssl musl libattr attr libcap2 libcap-getcap fakeroot lzip patch pkgconf libacl tar ca-certificates c-ares nghttp2-libs libcurl curl abuild jansson binutils libmagic file libgomp libatomic isl26 mpfr4 mpc1 gcc libstdc++-dev musl-dev libc-dev g++ make fortify-headers build-base libexpat git alpine-sdk clang16-headers libxml2 llvm16-libs clang16-libs llvm16-linker-tools clang16 libaio device-mapper-event-libs lvm2-libs lvm2 libfdisk libsmartcols cfdisk hfsprogs eudev-libs udev-init-scripts eudev mesa llvm15-libs libpciaccess libdrm musl-fts libelf mesa-glapi libxau libmd libbsd libxdmcp libxcb mesa-dri-gallium libevdev mtdev libinput-libs libinput-udev xf86-input-libinput encodings font-alias libfontenc libpng freetype mkfontscale fontconfig util-macros font-cursor-misc font-misc-misc libx11 wayland-libs-server mesa-gbm wayland-libs-client libxshmfence mesa-egl libxext libice libsm libxt libxmu xauth mcookie xmodmap xrdb xinit libxkbfile xkbcomp xkeyboard-config xorg-server-common libxfixes libxxf86vm mesa-gl libxfont2 libepoxy pixman libxcvt xorg-server kbd-misc kbd libxi libxtst xf86-input-synaptics alsa-ucm-conf alsa-lib fftw-single-libs alsa-utils brightnessctl shared-mime-info libjpeg-turbo libsharpyuv libwebp tiff gdk-pixbuf libnotify dunstify libxinerama libxrender libxrandr libxscrnsaver cairo libxft fribidi graphite2 harfbuzz pango wayland-libs-cursor dunst giflib libid3tag libwebpdemux imlib2 feh libSvtAv1Enc aom-libs libva libvdpau onevpl-libs ffmpeg-libavutil libdav1d libhwy lcms2 libjxl lame-libs opus soxr ffmpeg-libswresample libogg libtheora libvorbis libvpx libwebpmux x264-libs numactl x265-libs xvidcore ffmpeg-libavcodec sdl2 libunibreak libass libbluray mpg123-libs libopenmpt cjson mbedtls librist libsrt libssh libsodium libzmq ffmpeg-libavformat serd-libs sord-libs sratom lilv-libs glslang-libs libdovi spirv-tools shaderc vulkan-loader libplacebo ffmpeg-libpostproc ffmpeg-libswscale vidstab zimg ffmpeg-libavfilter libasyncns dbus-libs libltdl orc libflac libsndfile speexdsp tdb-libs libpulse v4l-utils-libs ffmpeg-libavdevice ffmpeg ffmpegthumbnailer libatk-1.0 hicolor-icon-theme gtk-update-icon-cache libxcomposite libxcursor libxdamage at-spi2-core libatk-bridge-2.0 cairo-gobject avahi-libs cups-libs wayland-libs-egl libxkbcommon gtk+3.0 geany htop fftw-double-libs imagemagick-libs imagemagick imagemagick-jpeg imagemagick-jxl imagemagick-tiff imagemagick-webp imagemagick-pango oniguruma jq libmpdclient mpc libao libcdio libcdio-paranoia faad2-libs fmt icu-data-full icu-libs libsamplerate jack libmad libmodplug libnfs libcamera-ipa libunwind yaml libcamera libuv roc-toolkit-libs webrtc-audio-processing pipewire-libs speex libshout talloc tevent samba-util-libs lmdb ldb skalibs utmps-libs linux-pam libwbclient samba-libs libsmbclient wavpack-libs mpd libxpresent libxv libarchive libdvdcss libdvdread libdvdnav luajit rubberband-libs sndio-libs uchardet-libs mpv boost1.82-filesystem boost1.82-thread boost1.82-locale boost1.82-program_options libtag ncmpcpp neofetch librsvg imagemagick-svg openbox-libs xcb-util startup-notification openbox libsigc++ glibmm atkmm sound-theme-freedesktop libcanberra libcanberra-gtk3 cairomm pangomm gtkmm3 json-glib libpulse-mainloop-glib pavucontrol playerctl psmisc mpdecimal python3 python3-pycache-pyc0 pyc python3-pyc libpcre2-16 qt5-qtbase rofi-themes xcb-util-image xcb-util-renderutil xcb-util-cursor xcb-util-wm libxkbcommon-x11 rofi libxxhash rsync rxvt-unicode-terminfo perl libptytty rxvt-unicode scrot desktop-file-utils libexif libxfce4util exo-libs libgudev libgtop xfconf libxfce4ui libxfce4panel thunar thunar-archive-plugin libtag_c thunar-media-tags-plugin thunar-volman tint2 bubblewrap dbus dbus-daemon-launch-helper xdg-dbus-proxy gcr-base libsecret gcr-ssh-agent gcr gnome-keyring libwpe libwpebackend-fdo libavif enchant2-libs flite cdparanoia-libs graphene gstreamer libcanberra-gstreamer gst-plugins-base openexr-libiex boost1.82-python3 imath openexr-libilmthread openexr-libopenexr soundtouch libraw1394 libusb libdc1394 libde265 tslib directfb faac fdk-aac libfreeaptx gsm libldac neon libnice openal-soft-libs openjpeg librtmp sbc spandsp libsrtp vo-aacenc vo-amrwbenc libzbar gst-plugins-bad harfbuzz-icu hyphen libmanette libseccomp gsettings-desktop-schemas duktape libproxy glib-networking libpsl libsoup3 libwoff2common libwoff2enc libxslt webkit2gtk-4.1 libgepub libgsf libopenraw poppler poppler-glib tumbler gc w3m w3m-image wireless-tools-libs wireless-tools xautolock xclip xset xprop xdg-utils xcb-util-keysyms qt5-qtbase-x11 qt5-qtdeclarative qt5-qtwayland wayland; do
              cd $pkg
              echo "Building package $(busybox basename $pkg)"
              { abuild -FrfqP "$dist" 2>&1 | busybox grep "ERROR:" | busybox grep -vi index || true; }
              cd ..
            done
            cd ..
            done
          cd ..
        shell: alpine.sh --root {0}
      - name: Build gearlock
        run: |
          export CBUILD=x86_64
          export PACKAGER_PRIVKEY=$(ls -d ~/.abuild/*.rsa | head -1)
          export REPODEST=$dist
          export DEBUG=1
          cd gearlock
          abuild -FrfqP "$dist" 2>&1 | busybox grep "ERROR:" | busybox grep -vi index || true
          cd ..
        shell: alpine.sh --root {0}
      - name: Artifact
        run: |
          mkdir -p dist
          find ./pkgs -type f -name "*.apk" -exec cp -t dist/ {} +
          cd dist/
          apk index -vU -o APKINDEX.tar.gz *.apk || true
          cd ..
        shell: alpine.sh --root {0}
      - name: Deploy
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: dist/*
