name: Package updates

on: push

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Self-clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: alpinelinux/aports
          path: aports
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup
        uses: jirutka/setup-alpine@v1.1.3
      - name: Install deps
        run: |
          apk add abuild abuild-rootbld findutils sed
          cd aports
          busybox find main community testing -name APKBUILD -exec sed -r -e 's|pkgdir"/lib/|pkgdir"/usr/lib/|g' -e 's|pkgdir"/bin/|pkgdir"/usr/bin/|g' -e 's|pkgdir"/sbin/|pkgdir"/usr/bin/|g' {} +
          export CBUILD=x86_64
          echo -e "\n" | abuild-keygen
          export PACKAGER_PRIVKEY=$(ls -d ~/.abuild/*.rsa)
          sh -c "for pkg in main/* community/* testing/*; do cd $pkg; abuild -Frf; cd ../..;done"
        shell: alpine.sh --root {0}
      - name: Deploy
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: ~/packages/*/x86_64/*.apk
