name: Package updates

on:
  push:
  workflow_dispatch:

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: alpinelinux/aports
          path: aports
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone gearlock
        uses: actions/checkout@v3
        with:
          repository: Yuunix-Team/gearlock-core
          path: gearlock
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup
        uses: jirutka/setup-alpine@v1.1.3
      - name: Install deps
        run: |
          apk add abuild abuild-rootbld findutils sed
          cd aports
          find main community testing -name APKBUILD -exec sed -ri -e 's|pkgdir"/lib(64)?/|pkgdir"/usr/lib/|g' -e 's|pkgdir"/s?bin/|pkgdir"/usr/bin/|g' {} +
          echo -e "\n" | abuild-keygen
          cd ..
          addgroup abuild || true
          addgroup $USER abuild || true
        shell: alpine.sh --root {0}
      - name: Build
        run: |
          export CBUILD=x86_64
          export PACKAGER_PRIVKEY=$(ls -d ~/.abuild/*.rsa | head -1)
          mkdir pkgs
          dist=$(ls -d ./pkgs)
          export REPODEST=$dist
          cd aports
          for pkg in main/*/ community/*/; do cd $pkg; echo "Building package ${pkg##*/}"; { abuild -FrfqP "$dist" 2>&1 | busybox grep "ERROR:" | busybox grep -vi index || true; }; cd ../..;done
          cd ..
        shell: alpine.sh --root {0}
      - name: Build gearlock
        run: |
          export CBUILD=x86_64
          export PACKAGER_PRIVKEY=$(ls -d ~/.abuild/*.rsa | head -1)
          export REPODEST=$dist
          export DEBUG=1
          cd gearlock
          abuild -FrfqP "$dist" 2>&1 | busybox grep "ERROR:" | busybox grep -vi index || true
          cd ..
        shell: alpine.sh --root {0}
      - name: Artifact
        run: |
          mkdir -p dist
          find ./pkgs -type f -name "*.apk" -exec cp -t dist/ {} +
          cd dist/
          apk index -vU -o APKINDEX.tar.gz *.apk || true
          cd ..
        shell: alpine.sh --root {0}
      - name: Deploy
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: dist/*
